### ISSUE TITLE
Design the basic interface with swapping out algorithms and parameters

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#1]
cc: @Nosferican @sglyon

The idea is to create a simple library that will generate a higher-order function for calculating expectations (i.e., mapping to the expectation operator in the math).  This could become a very complicated library if it (efficiently) dealt with all sorts of conditional and multi-variate exponentials, so lets keep things simple and start with univariate ones.

A starting point for the implementation is https://github.com/jlperla/ECON407_2018/blob/master/notebooks/expectations_integration.ipynb  which I used in rewriting some of the QuantEcon julia lecture notes (e.g. my Optimal growth rewrite in https://github.com/jlperla/ECON407_2018/blob/master/notebooks/optgrowth.ipynb )

As an example, the current implementation is something like
```julia
using QuantEcon, Distributions, QuadGK, NamedTuples, BenchmarkTools
function expectation(dist::Distributions.Normal{T}; n=20, kws...) where {T}
    nodes, weights = qnwnorm(n, [mean(dist)],[var(dist)])
    return f -> dot(f.(nodes), weights)  #Returns a function (of a function f)
end

#Then, for arbitrary distributions with a pdf function, we can  Gauss-Kronod adaptive quadrature.
#This is very precise, but does more calculations by default
function expectation(dist::D; kws...) where {D <: ContinuousUnivariateDistribution}
    #Uses Gauss-Kronod adaptive quadrature
    return f ->
        quadgk( x-> f(x) * pdf(dist,x) , minimum(dist), maximum(dist); kws...)[1] 
end

#For a discretely valued expectation, could just do the sums as a dot-product
function expectation(dist::D; kws...) where {D <: DiscreteUnivariateDistribution}
    @assert hasfinitesupport(dist) #Otherwise might need to modify to use a truncated pdf.    
    distsupport = support(dist)
    return f -> dot(pdf.(dist, distsupport), f.(distsupport))  
 end

#For convenience, version that takes a function as the first parameter
#Less useful if you want to cach the nodes/weights, etc., but notationally simple.
function expectation(f, dist::D; kws...) where {D <: UnivariateDistribution}
    E = expectation(dist; kws...) #Gets the appropriate expectation operator for dist
    return E(f) #calls the expectation with f
end
```
To use it, the current code looks like this.
```julia
#Can get an E and use it
dist = Normal(0.1, 2)
E = expectation(dist)

meanx = E(x -> x)
@show meanx

#Can define and pass in functions as well, not just anonymous
g(x) = x

varx = E(x -> x^2) - E(g)^2 #i.e. calculate the variance
@show varx

#Or can call `expectation` directly with a function as the first parameter
meanx2 = expectation(x -> x, dist)
@show meanx2
```

The problem with this simple design is that it makes it difficult to separate out the quadrature algorithm from the distribution itself.  What about this design instead for the interface?
```julia
abstract type QuadratureAlgorithm end
type AdaptiveQuadrature <: QuadratureAlgorithm end #e.g. Gauss-Kronod
type GaussianQuadrature <: QuadratureAlgorithm end; #e.g. n-point gaussian, Gauss-Laguerre, etc.
type FiniteDiscrete <: QuadratureAlgorithm end# e.g. baseline simple one for discrete, finite distributions
```
Then, we can use the variable argument keywords for parameters, providing defaults as required.  For example, something like
```julia
function expectation(dist::D, q::AdaptiveQuadrature; kws...) where {D <: ContinuousUnivariateDistribution}
    #Uses Gauss-Kronod adaptive quadrature
    return f ->
        quadgk( x-> f(x) * pdf(dist,x) , minimum(dist), maximum(dist); kws...)[1] 
end

function expectation(dist::Distributions.Normal{T}, q::GaussianQuadrature; n=20, kws...) where {T}
    nodes, weights = qnwnorm(n, [mean(dist)],[var(dist)])
    return f -> dot(f.(nodes), weights)
end
function expectation(dist::Distributions.Normal{T}, q::Q = GaussianQuadrature() ; kws...) where {T, Q <: QuadratureAlgorithm } #default
  expectation(dist, q ; kws...)
end
```
etc.

**Comment by jlperla** [comment]
Also see https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/quad.jl#L918 for a generic example, where a lot of the code in the file is ported from Miranda-Fackler

**Comment by jlperla** [comment]
I posted https://discourse.julialang.org/t/multiple-dispatch-design-with-different-algorithms-and-default-values/12358 to see if people can help with the design of the multiple-dispatch for this.

**Comment by sglyon** [comment]
Hey @jlperla thanks for starting the conversation here. Sorry for my late responses. I've been totally swamped as I prep for my dissertation defense.

I don't have anything to add in my few minutes right now, but I will continue to follow along and comment when I feel that I can contribute.

oh and thanks for pinging me on the conversation!

**Comment by jlperla** [comment]
Thanks @sglyon Coming down the home stretch!

Looking forward to your comments when we hit convergence on a few things, and you have more time.  Though I need you more for Interpolations.jl in the short 

I think that the basic design of the first iteration of the interface is good enough to make an implementation (which we can swap out).  I will close this issue and we can discuss a proposed interface once we have a set of tests.
