### ISSUE TITLE
Gauss-Legendre quadrature for arbitrary bounded continous univariate functions

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#11]
For this, write the `Gaussian` algorithm for the `UnivariateContinuousDistribution` to use Gauss-Legendre quadrature.  This works for any bounded support distribution, even if we want to do further specializations.

Note that if we setup the types correctly, then concrete types which are subsets of `UnivariateContinuousDistribution` (or whatever it is called in Distributions.jl) would pick up their own specializations.  In particular, normal, lognormal, etc.

For the quadrature approach itself:
- Need to throw a method-error if the support of the distribution is unbounded.
- See `http://quantecon.github.io/QuantEcon.jl/latest/api/QuantEcon.html#QuantEcon.qnwlege-Tuple{Int64,Real,Real}` for the call in QuantEcon, which can be swapped out later.

It may make sense to use this as the default algorithm for all continuous univariate functions, and not even implement the `Adaptive` quadrature.

**Comment by arnavs** [comment]
This is supported now.
