### ISSUE TITLE
Conditional expectation with markov chains

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#12]
See https://lectures.quantecon.org/jl/ifp.html

A key type of discrete expectation is something like
`E(f(X_{t+1} | X_t = x_t)` for a discrete distribution.

My thought is that this can be efficiently handled in the interface by something along the lines of
```julia
P = #... get markov chain in one way or another
E = conditional_expectation(P)

#Now this can be called as
```julia
#E(f(X_{t+1}) | X_t = 2)
E(x-> f(x), 2)
#Or if you have the vector of nodes `x` matching the iteration.
E(2) * f.(x)
```
It may also be possible to hook into the `MarkovChain` features in `QuantEcon` such as that of https://github.com/QuantEcon/QuantEcon.jl/blob/785c71b99b04c49c8638d499591584c1e33f3745/src/markov/mc_tools.jl#L19-L30 for the "state vector" instead of giving the ordinal position as above

**Comment by arnavs** [comment]
This may be worth working on now, seeing as we're starting to modernize the lectures. @Nosferican, let me know if you'd like to talk about this sometime (or just put your thoughts here).

**Comment by Nosferican** [comment]
What about having this package as a dependency for QuantEcon.jl? Then that might help reduce the clutter in that package... I just worked on `gridmake`... modernizing that function reduced the LoC from 55 to a one liner.

**Comment by arnavs** [comment]
Yeah, I think that’s the idea. The problem I see is we want to avoid circular dependencies, if we use the Markov Chain object in there.

**Comment by Nosferican** [comment]
Take a look at the Markov Chain code in QuantEcon to see what you think might work best.

**Comment by jlperla** [comment]
I think that in the medium term, the markov chain code should be in its own library as it is a self-contained thing.

I also think that we are better off leaving the markov chain expectations the way they are in the current codet, and out of the expectations. If anything, expectations should be extended to handle multivariate distributions to remove the need for those in QuantEcon.

**Comment by arnavs** [comment]
Frankly, I think the best outcome would be to devolve the Markov stuff to somewhere in the `JuliaStats` organization. We could also talk with the owner of [this package](https://github.com/wangnangg/MarkovChains.jl), which was created last month, and looks like the only standalone Markov package in the Julia ecosystem. 

In terms of the expectation, I think we can support `E(f, state; delta_t = 1)` or something, like @jlperla said.

**Comment by jlperla** [comment]
I think we should leave the markov chain stuff alone for now.  The gain in notational clarity is not worth the trouble, especially if the whole markov chain library changes in the near future.

**Comment by arnavs** [comment]
Fair enough (and just saw your earlier comments). And I couldn't think of a way to avoid circular dependencies anyway. So we'll leave this be for now.

**Comment by arnavs** [comment]
This issue has been open for about a year and a half, so closing.
