### ISSUE TITLE
Add the convenience call with a function

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#17]
One small thing first: the idiom in Julia is generally for simple functions to avoid the `function`, `return` and `end`.  That is instead of 
```julia
function expectation(dist::D, alg::Type{FiniteDiscrete} = FiniteDiscrete; kwargs...) where {D <: DiscreteUnivariateDistribution}
    return _expectation(dist, alg; kwargs...)
end
```
you would do something like
```julia
expectation(dist::D, alg::Type{FiniteDiscrete} = FiniteDiscrete; kwargs...) where {D <: DiscreteUnivariateDistribution} = _expectation(dist, alg; kwargs...)
```
-----
Now, I think we can now add in the overload of `expectation` which takes in a function.  Basically this just mak

I believe you will need one of these for every `expectation` call, since otherwise it would not have the default parameters handled correctly.  Not a big deal.  For example in the above one it is something like
```julia
expectation(f::Function, dist::D, alg::Type{FiniteDiscrete} = FiniteDiscrete; kwargs...) where {D <: DiscreteUnivariateDistribution} = expectation(dist, alg;kwargs...)(f)
```

**Comment by Nosferican** [comment]
The function doesn't seem to be using `D` so I would write it as
```
expectation(f::Function,
            dist::DiscreteUnivariateDistribution,
            alg::Type{FiniteDiscrete} = FiniteDiscrete;
            kwargs...) = expectation(dist, alg; kwargs...)(f)
```
I must confess I need to check the code for the particulars about `FiniteDiscrete <: ExplicitQuadratureAlgorithm` and keyword arguments, but it might make sense to pass `FiniteDiscrete(kwargs)` if the keyword arguments relate to the algorithm. That would allow to dispatch on the `alg::ExplicitQuadratureAlgorithm`.

**Comment by jlperla** [comment]
Check out the current interfaces from a user perspective.  It is *so much* easier for users if they can just throw in any arguments in keywords instead of worrying about structures with default parameters/etc. The other issue is that we can use the same algorithm tag for a conceptual algorithm which make have different parameters for different types of distributions.  The users don't need to even know what the default algorithm is.  If they want to change the number of nodes `N` they can just go 
```julia
dist = ....#Any supported distribution
E = expectation(dist, N=20) #change the number of nodes
```

**Comment by arnavs** [comment]
@jlperla @Nosferican Done.
