### ISSUE TITLE
Add in docstrings and figure out how to generate package documentation

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#18]
Now that the package has the basic functionality and interface, we can add in docstrings, and figure out how to generate docs... 

I believe https://github.com/JuliaDocs/Documenter.jl is the way to generate docs, and it is probably worth figuring out.

**Comment by Nosferican** [comment]
Documenter is great. Is really easy to use and you can find a lot of packages for examples. I can help with that too. It does rely on passing Travis CI since the hosting is triggered with `after success`.

**Comment by jlperla** [comment]
Perfect! Sounds like some time well spent figuring it out.

**Comment by arnavs** [comment]
@jlperla In particular, there's a nice feedback between `Literate.jl` and Documenter that I haven't figured out yet. But we should- I always those those packages were more legit than the ones whose docs were splatted into README.

**Comment by jlperla** [comment]
Speaking of docs splatted in the README.... if getting Documenter.jl setup with some simple functionality is relatively easy, maybe we could do it for NLsolve and do a quick merge of some of the docs in the README into it?  If we are adding in fixed-point examples to the end of the README, then the current docs are pretty cluttered.

**Comment by arnavs** [comment]
OK, I put together some docs using Documenter, and added docstrings to all functions and types. There are currently some errors (no side-effects between blocks), which I am ironing out. Also moved a lot of stuff out of the README that should really be in the docs. 

Let me know what you think. Stuff at the bottom (contact info, etc.) is just temporary and will change once others maintain or if you want to change it.

**Comment by jlperla** [comment]
Looks great to me.  How difficult was using Documenter?  Would it be a modest amount of work to fudge `NLsolve.jl` so that the fixed-point examples were in docs instead of a huge readme?

**Comment by arnavs** [comment]
Not that hard. Basically copy their boilerplate, do some git setup, and then write a markdown file with the docs. Most of the time spent came down to two things, one of them being forgetting `using Expectations`. 

It would be pretty easy to put the NLsolve docs in that way. I'll close this one for now, and then we can talk about `NLsolve.jl`
