### ISSUE TITLE
Bug when computing simple expectations

### ISSUE THREAD

**Issue by IljaK91** [QuantEcon/Expectations.jl#23]
I have encountered a bug today:

```
using Distributions, Expectations
E    = expectation(Normal(1, 1))
E(x -> x)

julia> E(x -> x)
5.778544334733716e-17
```

where it clearly should be 1. I can have a look tomorrow to figure out what is happening.

**Comment by Nosferican** [comment]
Thanks.

**Comment by arnavs** [comment]
Thanks for posting @IljaK91, will look into this right now.

**Comment by arnavs** [comment]
This was a straight-up math error with the order of operations on something. I pushed a fix to `master` and added a test case. Will go through and make sure we have enough non-standard parameter cases in there as sanity checks.

**Comment by arnavs** [comment]
Tagged a new release https://github.com/econtoolkit/Expectations.jl/tree/v1.0.2 to incorporate these fixes, and more tests.
