### ISSUE TITLE
Should the newton-coates work with an infinite support distribution?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#25]
The docs had the following, which I removed:

If nodes are given, it will calculate using Newton-Coates quadrature (e.g. Trapezoidal)
```julia
x = -10:0.2:10
f(x) = x^2
E = expectation(dist, x)
3 * E(f) == 3 * E * f.(x)
```

But is that valid?  the `dist` in that case was a Normal.  If that works, then I think we need to be more careful and reject if the bounds don't match, etc.

**Comment by arnavs** [comment]
@jlperla How about a check that the bounds include a minimum amount of probability mass? i.e., we have some keyword argument `mass = 0.99` that we check against.

**Comment by jlperla** [comment]
No, just check the `support(dist) `in the Newton Coates code. If one side is infinity or minus infinity, then throw an error

**Comment by arnavs** [comment]
OK, done in the above commit.
