### ISSUE TITLE
Some readings on Gaussian quadrature

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#3]
https://en.wikipedia.org/wiki/Gaussian_quadrature

There are a few key points about Gaussian quadrature:
- These are able to integrate functions with infinite support on one or both ends.  This is important when finding the expectations of distributions defined on `[-infinity, infinity]`,  `[0, \infinity]`, etc.  So you will need to take care on choosing the right one 
- See https://juliastats.github.io/Distributions.jl/latest/univariate.html and in particular the `maximum` and `minimum` of the support
- Sometimes the weights of the PDF and the weights of the quadrature nodes are easily calculated together (or the libraries do it all at once).  What is important for calculating the expectations is the ability to cache the weighting vector and nodes, so you can use the appropirate code/library to do it.

**Comment by jlperla** [comment]
- See https://github.com/ajt60gaibb/FastGaussQuadrature.jl
- See https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/quad.jl for the existing QuantEcon code.
  - I believe this is a port of the Miranda and Fackler code.
- It wasn't around with Spencer wrote the original code, but I think it may be possible to put in newer quadrature libraries.
  - One of them is the `FastGaussQuadrature.jl` library.  This library is great for calculating the nodes and weights, but you need to do the scaling yourself to domains other than `[-1, 1]`, I believe.

**Comment by arnavs** [comment]
OK, sounds good. Will read through these.

**Comment by jlperla** [comment]
I also found https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl which had the similar idea to this.
