### ISSUE TITLE
Erlang

### ISSUE THREAD

**Issue by tbeason** [QuantEcon/Expectations.jl#33]
Erlang dist is a special case of Gamma dist with integer first parameter. The existing implementation that works for Gamma should also be used for Erlang then, correct? Right now it just fails.

I naively encountered this because the sum of Exponential draws has an Erlang distribution.

**Comment by arnavs** [comment]
Hi @tbeason, thanks for this suggestion. 

I'll work on it today.

**Comment by arnavs** [comment]
OK, this will be in the next release. Should be out by the end of the day. 

This issue also uncovered a bug in our implementation of Gamma distributions with non-unity `theta` parameters, which is now fixed. 

Closing now.
