### ISSUE TITLE
Way to get the weights and nodes for an expectation operator?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#4]
It is very convenient to do the following
```julia
E = expectation(Normal(0.0, 1.0))
E(x-> x^2)
```
However, sometimes you would prefer to instead directly get the nodes and weights for the expectation operator (which is then a linear operator).

Because of this, instead of `expectation(...)` returning a function, perhaps it should return an operator "type" which is callable (and hence can act as a function) but has other methods.  In particular,
```julia
E = expectation(Normal(0.0, 1.0))
E(x-> x^2)
nodes(E) #returns a vector of the underlying nodes associated with the operator
weights(E) #returns the weights.
```

**Comment by arnavs** [comment]
Makes sense. Is there any distinction (in CS-land) between an operator and a `function f(x::Function)::Function`?

**Comment by jlperla** [comment]
Well, I meant to use operator in the mathematical sense, but this is how you make an object callable https://docs.julialang.org/en/v0.6.0/manual/methods/#Function-like-objects-1  
Where the argument would be a function.

The only thing to keep in mind with the design of the types is that `nodes` and `weights` do not apply to all quadrature algorithms.  For example, with adaptive quadrature it doesn't make any sense, so we would need to have the type returned from the `expectation` have different super-types depending on the algorithm.  But we can design those parts of the interface later.

**Comment by arnavs** [comment]
Gotcha. Thanks for the link; could easily see myself struggling with that. And makes sense re different algos.

**Comment by arnavs** [comment]
This issue is now implemented; e.g. 

```
# Callable behavior for the object. Parameters because we cannot add methods to an abstract type. 
function (e::IterableExpectation{NT, WT})(f::Function; kwargs...) where {NT, WT}
    applicable(f, rand([e.nodes...])) || throw(MethodError("The function doesn't accept elements from the distribution's support."))
    return dot(f.(e.nodes), e.weights; kwargs...) 
end 
```
