### ISSUE TITLE
Feature request: Finite mixture distributions

### ISSUE THREAD

**Issue by nignatiadis** [QuantEcon/Expectations.jl#42]
I really love this package! 

One feature that would be great to have would be to extend `expectation` to mixture models. For example, the following cannot be integrated by this package right now:
```
 MixtureModel([Uniform(), Normal()])
```
But each individual component can be integrated, so it is possible to manually average these two. It would be great if this could be automated through the `expectation` operator.

**Comment by arnavs** [comment]
Hi @nignatiadis, thanks for the suggestion. I think this is certainly doable. Will probably add this over the weekend. 

Glad you are enjoying the package!

**Comment by nignatiadis** [comment]
That sounds great, thank you!!!

**Comment by pkofod** [comment]
You need to specify the mixing probability as well. Is it cleaner to have one be implicit, or normalize the input to sum to 1? The latter has a slightly higher chance of producing bugs imo. You could be required to specify the first N-1 probabilities.

**Comment by nignatiadis** [comment]
The`MixtureModel` type from `Distributions.jl` requires the full vector of mixing probabilities and throws an error if they do not sum to 1 (and defaults to equal mixing probabilities).

```julia
julia> MixtureModel([Uniform(), Normal()])
MixtureModel{Distribution{Univariate,Continuous}}(K = 2)
components[1] (prior = 0.5000): Uniform{Float64}(a=0.0, b=1.0)
components[2] (prior = 0.5000): ^[[DNormal{Float64}(μ=0.0, σ=1.0)


julia> MixtureModel([Uniform(), Normal()], [0.4; 0.6])
MixtureModel{Distribution{Univariate,Continuous}}(K = 2)
components[1] (prior = 0.4000): Uniform{Float64}(a=0.0, b=1.0)
components[2] (prior = 0.6000): Normal{Float64}(μ=0.0, σ=1.0)


julia> MixtureModel([Uniform(), Normal()], [0.4; 0.7])
ERROR: ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.
```

**Comment by pkofod** [comment]
Oh, I wasn't aware. Great.

**Comment by arnavs** [comment]
Do you think it's reasonable for the `MixtureExpectation` convenience constructor to use the default settings for each distribution (or `kwargs` applied to all of them, like a grid?) 

If you want to specialize for each component, you can construct the expectations by hand and chain them together, e.g. 

`MixtureExpectation([Es...], [Weights...])`

Otherwise we'd have to pass each distribution's arguments and kwargs to it.

**Comment by arnavs** [comment]
@nignatiadis I added this in version `1.3.0`. If we want to tweak it, we can issue a patch release.

**Comment by nignatiadis** [comment]
This looks great to me; thank you!!
