### ISSUE TITLE
Feature request: Addition of expectations

### ISSUE THREAD

**Issue by nignatiadis** [QuantEcon/Expectations.jl#46]
This is a follow-up to #42.  I just realized that `MixtureExpectation` implements addition of expectations:

```julia
julia> e1 = expectation(Normal(1.0))
julia> e2 = expectation(Uniform())
julia> e1pe2 = MixtureExpectation([e1,e2],[1.0,1.0])
julia> e1pe2(identity) == e1(identity) + e2(identity)
true
```
So adding methods for `+(e1::Expectation, e2::Expectation)` would be both elegant from a mathematical perspective (especially since `*` is already implemented) and also quite practical/useful!

**Comment by arnavs** [comment]
Huh. Yeah, you're right. That's a good point. 

Will do. Thanks for the good suggestions.

**Comment by arnavs** [comment]
Done @nignatiadis

**Comment by arnavs** [comment]
Note that a consequence is that we can add `MixtureExpectation`s and `IterableExpectation`s, e.g. 

```
julia> e1 = expectation(Normal());

julia> e2 = expectation(Uniform());

julia> e3 = expectation(Gamma());

julia> E = e1 + (e2 + e3);

julia> typeof(E.expectations[2])
MixtureExpectation{Tuple{IterableExpectation{Array{Float64,1},Array{Float64,1}},IterableExpectation{Array{Float64,1},Array{Float64,1}}},Array{Float64,1}}

julia> E(x -> x) == e1(identity) + e2(identity) + e3(identity)
true
```

**Comment by nignatiadis** [comment]
This is super cool!! Thank you a lot!
