### ISSUE TITLE
Compat.LinearAlgebra is deprecated

### ISSUE THREAD

**Issue by cossio** [QuantEcon/Expectations.jl#49]
Got this warning when `using Expectations` for the first time (at precompilation):

```
WARNING: Compat.LinearAlgebra is deprecated, use LinearAlgebra instead.
  likely near ~/.julia/packages/Expectations/RkwWa/src/Expectations.jl:7
```

**Comment by arnavs** [comment]
Thanks. We kept this around for v0.6 and v0.7 support, but I think it can now be removed. 

Done in ebb58ba.

**Comment by cossio** [comment]
Thank you.
