### ISSUE TITLE
performance of IteratableExpectation

### ISSUE THREAD

**Issue by FuZhiyu** [QuantEcon/Expectations.jl#58]
I find the performance of `IteratableExpectation` leaves quite some room for improvement. 

```Julia
using Expectations
g(a) = a^2
E = expectation(Normal(), Gaussian; n =10)
@btime g(1.0) #   0.015 ns (0 allocations: 0 bytes)
@btime $E($g) # 247.751 ns (6 allocations: 256 bytes)
```
it's >1000x slower than it should be.

The source code of expectation is as follows:
```Julia
function (e::IterableExpectation{NT,WT})(f::Function; kwargs...) where {NT,WT}
    applicable(f, rand(nodes(e))) || throw(ArgumentError("The function doesn't accept elements from the distribution's support."))
    return dot(f.(nodes(e)), weights(e))
end
```

Here is the implementation in the source. I guess at least we could kill unnecessary allocation by using for loops instead of dot product. Also, as it's often called in the innermost loop of a performance sensitive code, probably it's better not to check whether `f` is applicable every time? At least we could avoid `rand`.

Here is my own version used in projects: 
```Julia
function (e::IterableExpectation{NT,WT})(f::Function, ::Nothing) where {NT,WT}
    # nvec, wvec = nodes(e), weights(e)
    nvec, wvec = nodes(e), weights(e)
    E = f(nvec[1]) * wvec[1]
    @inbounds for i in 2:length(nvec)
        n, w = nvec[i], wvec[i]
        E += f(n) * w
    end
    return E
end

@btime $E($g, nothing) # 9.722 ns (0 allocations: 0 bytes)
```
The performance makes much more sense now.

**Comment by jlperla** [comment]
@FuZhiyu  Looks great.  Can you make a PR?

**Comment by arnavs** [comment]
Looks good to me. The `applicable` was just a sanity check anyway; if `f` doesn't have the distribution's support in its domain, it's reasonable to say that's `f`'s problem. 

I'm surprised that `dot` is so slow, given that it's a common function that they provide. But numbers don't lie!

And good idea to drop bounds checking.
