### ISSUE TITLE
Expectation with pre-existing grid and the trapezoidal rule

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#6]
Something that comes up a lot in macro is the need to calculate expectations where a (often irregular) grid is predefined.  For example, something like
```julia
using Distributions
x_max = 2.0
d = Truncated(Exponential(0.1), 0.0, x_max) #truncated exponential
x = [linspace(0.0, 1.0, 10); linspace(1.01, x_max, 20) #match support
E = expectation(d, x, :trapezoidal)

#Calculate expectation E(x^2)
h(x) = x^2
val = E(h)

#Or using the weights yourself.
val = dot(weights(E), h.(x))
```

Note that there could be dispatching in `expectation(d, x, :trapezoidal)` depending on if `x` is an `AbstractVector` vs. a `StepRangeLen` or `UnitRange`.  In the case of the latter, it could provide the (simpler) regular grid trapezoidal rule.  Which should probably be a lazy iterator rather than an actual vector.

**Comment by jlperla** [comment]
I think that we should also have `:trapezoidal` as the default algorithm type with an `x` as either an abstract vector, steprangelen, or unitrange.  We can add things like `:simpsons` much later.
So then the above could just be  `E = expectation(d, x)` instead.

**Comment by arnavs** [comment]
I think this is done now. @jlperla. If corrects, maybe we could close this and create a new issue for dispatching based on uniform vs. irregular grids. 

### Code
```
# Dispatcher.
function expectation(dist::D, nodes::NT, alg::Type{<:ExplicitQuadratureAlgorithm} = Trapezoidal; kwargs...) where {D <: ContinuousUnivariateDistribution, NT}
    return _expectation(dist, nodes, alg; kwargs...)
end

# Trapezoidal general behavior. 
function _expectation(dist, nodes, alg::Type{Trapezoidal}; kwargs...)
    M = length(nodes)
    Δ = diff(nodes)
    prepend!(Δ, NaN) # To keep the indexing straight. Now, Δ[2] = Δ_2 = z_2 - z_1. And NaN will throw an error if we try to use it.
    f = x -> pdf(dist, x)
    f_vec = f.(nodes)
    interiorWeights = [f_vec[i]/2 * (Δ[i] + Δ[i+1]) for i = 2:M-1]
    allWeights = [f_vec[1]/2 * Δ[2]; interiorWeights; f_vec[M]/2 * Δ[M]]
    return IterableExpectation(nodes, allWeights)
end 
```

### Tests
```
# Test trapezoidal for truncated normal. 
testDist7 = Truncated(Normal(), -5, 5)
z = -5:0.1:5
E_7 = expectation(testDist7, z)
E_8 = expectation(testDist7, z, Trapezoidal)
@test E_7.nodes == E_8.nodes && E_7.weights == E_8.weights
@test E_7(x -> x) ≈ mean(testDist7) atol = 1e-10
squares = [x^2 for x in rand(testDist7, 10^7)]
@test E_7(x -> x^2) ≈ mean(squares) atol = 1e-3
```

**Comment by Nosferican** [comment]
`f_vec = pdf.(Ref(dist), nodes)` should work in Julia 0.7 without deprecations. Check without the `Ref` in case it is not needed.

**Comment by jlperla** [comment]
For this one:  the key is to distinguish between regular and irregular trapezoidal quadrature.  See #9 for a discussion of the generic types, but I think it is basically:
```
# Trapezoidal general behavior. 
function _expectation(dist, nodes::AbstractArray, alg::Type{Trapezoidal}; kwargs...)
function _expectation(dist, nodes::AbstractRange, alg::Type{Trapezoidal}; kwargs...)
```
where what you have written is the abstractarray.  For the abstractrange, you can use `first(nodes)`, `last(nodes)` etc. and perhaps `step(nodes)`... or do it yourself with the `first,last,length`.

**Comment by arnavs** [comment]
Gotcha.

**Comment by jlperla** [comment]
To be clear there:  in the `AbstractRange` you can just have the weights as the usual `1,2,2,2,.....1` times whatever the scaling factor is from the domain.  I think the weights there can be kept as a vector for now, but ultimately it could be done with a special lazy iterator.

**Comment by jlperla** [comment]
Sounds great.  @ArnavSood   it is a decent probably that any function in julia has (or will have) broadcasting support, so in case it was't clear, he wants you to use
```
f = x -> pdf(dist, x)
    f_vec = f.(nodes)
# Replace with 
f_vec = pdf.(dist, nodes)
```
@Nosferican  In general, how do we know if `Ref` is needed in Julia?  What does it do exactly?  I am having a lot of trouble understanding code with it these days as I thought that julia's semantics didn't involve copying things unnecessarily?

**Comment by arnavs** [comment]
@jlperla Sounds good on both counts. Will implement.

**Comment by Nosferican** [comment]
From the `broadcast` docstring,
```
Broadcasting applies the function f over the elements of the container arguments and the scalars themselves in
  As. Singleton and missing dimensions are expanded to match the extents of the other arguments by virtually
  repeating the value. By default, only a limited number of types are considered scalars, including Numbers,
  Strings, Symbols, Types, Functions and some common singletons like missing and nothing. All other arguments are
  iterated over or indexed into elementwise.
```
using the example in the docstring to illustrate the difference,
```
(+).([[0,2], [1,3]], Ref{Vector{Int}}([1,-1]))
2-element Array{Array{Int64,1},1}:
 [1, 1]
 [2, 2]
(+).([[0,2], [1,3]], [1,-1])
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = _broadcast_getindex_evalf at broadcast.jl:579 [inlined]
└ @ Core ./broadcast.jl:579
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = _broadcast_getindex_evalf at broadcast.jl:579 [inlined]
└ @ Core ./broadcast.jl:579
2-element Array{Array{Int64,1},1}:
 [1, 3]
 [0, 2]
```
the warning as it relates to this case,
```
pdf.(d, nodes)
┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::Normal{Float64}` with `Ref(x)` to ensure they broadcast as "scalar" elements.
```
if it were the case of pdf.(::AbstractVector{<:Distribution}, ::AbstractVector{<:Real}) the `Ref` would not be required such as
```
pdf.(Normal.(rand(10)), rand(10))
```

**Comment by arnavs** [comment]
OK, updated the code to use broadcasting where appropriate (with `Ref`, as per your explanation) and to dispatch for uniform grids on `StepRangeLen` (as `Range` is deprecated in 0.7, and `AbstractRange` not implemented in 0.6) 

@Nosferican - This could be a `REQUIRE` issue, but my 0.7 builds on Travis are failing on the QuantEcon import. See [here](https://travis-ci.org/econtoolkit/Expectations.jl/jobs/405127708#L831). Have you seen this issue?

**Comment by Nosferican** [comment]
I am not with my computer at the moment, but you should probably use `AbstractRange` and use Compat.

I don’t think QuantEcon.jl is supporting 0.7/nightly at the moment. Is there a branch with 0.7 support?

**Comment by arnavs** [comment]
@Nosferican Sounds good. And no, but there is one for 0.4 support :) 

What we can do is make sure that this package works for both, and configure all the package management magic to sort that out. Then, when QuantEcon is good on 0.7, integration should be seamless.

**Comment by Nosferican** [comment]
You can divide the test scripts to test all the non-QuantEcon.jl tests and leave the rest for when QuantEcon updates. I will make an issue to track that and let you know when it gets tagged. A few of these routines are used in the lectures without QuantEcon code so I can work with those as soon as the last features are ready here.

**Comment by arnavs** [comment]
Perfect.

**Comment by arnavs** [comment]
OK, @jlperla @Nosferican, v0.1.0 is now our first tagged release with support for v0.6 and v0.7, both of which are okayed by Travis. This is the version with no QuantEcon dependencies. Gaussian quadrature for all smooth distributions tested is accurate to 1e-12. So, will close this issue. 🎉
