### ISSUE TITLE
question: is it possible to compute conditional expectations?

### ISSUE THREAD

**Issue by hdavid16** [QuantEcon/Expectations.jl#61]
For example, `E[dist(X) | X > a]`. 

If this is not possible, can I find the expectation of a truncated distribution?

**Comment by jlperla** [comment]
It should be possible to pass in a (two sided) truncated distribution - as it is just a distribution.  See https://juliastats.org/Distributions.jl/latest/truncate/  for example `Gauss-Legendre` should be used automatically in that case and you could tweak it.

**Comment by hdavid16** [comment]
It fails:

```julia
julia> using Distributions, Expectations, StatsBase

julia> f=Normal()
Normal{Float64}(μ=0.0, σ=1.0)

julia> expectation(x->x,f) #expectation of f(x) works (~0)
-5.028942338420413e-18

julia> mean(f) #expectation of f(x) computed with mean
0.0

julia> g=truncated(f,0.5,Inf) #try truncating f to get the conditional expectation for x>0.5
Truncated(Normal{Float64}(μ=0.0, σ=1.0), range=(0.5, Inf))

julia> expectation(x->x,g) #expectation of f(x) fails because of upper bound
ERROR: ArgumentError: The distribution must be defined on a compact interval.
Stacktrace:
 [1] _expectation(dist::Truncated{Normal{Float64}, Continuous, Float64}, alg::Type{Gaussian}; n::Int64, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Expectations C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:99
 [2] _expectation
   @ C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:97 [inlined]
 [3] #expectation#3
   @ C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:89 [inlined]
 [4] expectation
   @ C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:89 [inlined]
 [5] expectation(f::Function, dist::Truncated{Normal{Float64}, Continuous, Float64}, alg::Type{Gaussian}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Expectations C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:303
 [6] expectation (repeats 2 times)
   @ C:\Users\UB01382\.julia\packages\Expectations\KqWVw\src\iterable.jl:303 [inlined]
 [7] top-level scope
   @ REPL[22]:1

julia> mean(g) #expectation of truncated f(x) works (equivalent to E[f(x) | x>0.5])
1.1410777703680648

julia> h=truncated(f,0.5,1e9) #try setting an upper bound that is not Inf
Truncated(Normal{Float64}(μ=0.0, σ=1.0), range=(0.5, 1.0e9))

julia> expectation(x->x,h) #expectation fails
0.0

julia> mean(h) #mean works
1.1410777703680648
```

**Comment by jlperla** [comment]
Yeah, it isn't going to work without a two sided truncation and 1e9 is far too large.  Take a look at the weights and nodes and I bet you will see why it couldn't possible work wihtout going to a very high number of parameters.

If you have a left-truncated Normal, then you might want to figure out what the quadrature rules are for that and do it directly with https://github.com/JuliaApproximation/FastGaussQuadrature.jl

If you figure it out, you could also submit support in this package.  ALl it really does is wrap those quadrature rules.  See https://github.com/QuantEcon/Expectations.jl/blob/master/src/iterable.jl#L153-L161  for example.

YOu would just need to dispatch on the truncated normal and then check if it is right/left/two-sided truncation.

**Comment by hdavid16** [comment]
Ok. I'll stick with `mean` to get the conditional expectation of `f(X)` for now.
