### ISSUE TITLE
Any plans/timeline for supporting multivariate distributions?

### ISSUE THREAD

**Issue by churli** [QuantEcon/Expectations.jl#69]
As per the title, is there any plan/timeline for supporting multivariate distributions as well?

Thanks! :)

**Comment by arnavs** [comment]
Hi @churli, 

Glad you like the package `:-)`. I think the most feasible path for that would be to hire an RA to do it. The devs are largely working on other stuff and only doing "life support" updates (compat, etc.).

Generalizing the existing algorithms to multivariate versions of the same distribution shouldn't be hard, so I'll see if there are any funds for that kind of project. 

Arnav
