### ISSUE TITLE
Multiplication by an expectation object as inner product?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#7]
Think through a common example with #6 
```
using Distributions
x_max = 2.0
d = Truncated(Exponential(0.1), 0.0, x_max) #truncated exponential
x = [linspace(0.0, 1.0, 10); linspace(1.01, x_max, 20) #match support
E = expectation(d, x, :trapezoidal)

#Calculate expectation E(x^2)
h(x) = x^2
val = E(h)

#Or using the weights yourself.
val = dot(weights(E), h.(x))
```
Now, in algorithms we often have the `h(x)` function pre-calculated on the set of nodes `x`.  In that case,  consider the notation
```julia
hvals = h.(x) #presumably calculated in a different 
E_val = E * hvals
E_val == dot(weights(E), h.(x)))
```
To do this for an expectation operator (subtype of `AbstractExpectation`), you just need to add something like 
```
Base.*(E::AbstractExpectation, v::AbstractVector) = dot(weights(E), v)
```

**Comment by jlperla** [comment]
Actually, I think this should be slightly different.  
where `v` is an iterable.
```
Base.*(E::AbstractIterableExpectation, v) = dot(weights(E), v)
```
I am not sure what the abstract types might be, but note that https://github.com/JuliaLang/julia/blob/faee1df893060dda3dad7fbaeb1c46d86528ead2/stdlib/LinearAlgebra/src/generic.jl#L627-L650 doesn't constrain it at all.

What this allows us to do is apply the expectation to a whole vector of pre-filled functions and then multiple a matrix.

For this reason, I this than the implementation should probably be
```
Base.*(E::AbstractIterableExpectation, v) = weights(E)' * v
```

**Comment by arnavs** [comment]
@jlperla As discussed, see implementation and passing tests below. Let me know if this looks correct, or if anything needs to change. 

### Code
```
# Linear operator behavior.
import Base.*

# Right-multiplying an expectation by a vector. 
function *(e::IterableExpectation, h::AbstractArray)
    return h' * weights(e)
end 

# Left-multiplying an expectation by a scalar.
function *(r::Real, e::IterableExpectation)
    return IterableExpectation(e.nodes, r * e.weights) # Necessary because, for example, multiplying UnitRange * 2 = StepRange
end
```

### Tests 
```
# Test for linear operator behavior. 
h(x) = 2*x
z = E_1.nodes
@test E_1 * h.(z) == E_1(x -> 2*x) # Right-multiplying only. 
@test 2E_1.weights == 2*E_1.weights# Left-multiplying only. 
@test 3E_1*z == (3E_1) * z == 3*(E_1 * z) # Linearity. 
@test_throws DimensionMismatch h.(z) * E_1.nodes # Test non-commutativity of operator. 
```
