### ISSUE TITLE
Generic types for the `AbstractIterableExpectation` type and `OrdinalRange` for regular grids.

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#9]
This is useful for #6 primarily, but also #4.

I did a little research for the abstract types we would want for the `weights` and `nodes`, and the ranges used in some of this.

The `AbstractRange` type has the function `step(r)` 

The abstract type `OrdinalRange`  seems to be what we are thinking about for representing ranges for grids.  The functions we can rely on in its interface are:
- `first(r)` to get the first element of `r`
- `last(r)` to get the last element of `r`
- `length(r)` to get the number of steps in `r`.
- `iterate(r)` to iterate it (which is typically just used in loops or higher order functions using loops).

However, there is also `LinRange <: AbstractRange` which seems to have the same set of methods, but would be missing if we only used `OrdinalRange`.

So, my suggestion is that dispatching relies on `AbstractRange` for now, but assumes these all exist, and is likely to change to `OrdinalRange` if `LinRange` is deprecated or changed.

What this means is that if we are designing the interface with the fixed grid (e.g. Trapezoidal) then we can write just pass in that range to encompass all information about the range.  For example,
- `expectation(d, 0.0:0.1:1.0)` for some `d` a univariate, continuous distribution or `expectation(d, linspace(0.0, 1.0, 10))`
- This would dispatch on the `AbstractRange` for the 2nd parameter, with the `Trapezoidal` as the default.
- We know that this is a constant step size algorithm, so can use the trapezoidal rules for a regular grid (i.e., the `1, 2, 2, ... 1` weighting).  It should throw an `ArgumentError` if `first(r) != minimum(d)` and `last(r) != maximum(d).  We could also define the 3/8 simpsons rule and other versions relatively easily.
- On the other hand, if we were passed `expectation(d, [0.0 0.1 0.2 0.33 0.4 0.8 1.0])` then we could dispatch based on `AbstractArray` instead, and use the irregular trap rules.  And if the user went `expectation(d, collect(0.0:0.1:1.0))` then it would become an array and there would be no way to turn this into a regular grid.

**Comment by jlperla** [comment]
This is being discussed right now in https://github.com/JuliaLang/julia/pull/28115 which we can check in on.
The summary is:
  - Ordinal ranges are intended for “discrete” datatypes that cannot represent values smaller than `oneunit`, and have steps that are multiples of that unit.  

`AbstractRange` is intended for step sizes potentially smaller than one unit.

**Comment by arnavs** [comment]
@jlperla Can we close this? The current code has an irregular method for `AbstractArray`s, and a regular one for `AbstractRange`s.

**Comment by jlperla** [comment]
Yup.  Done.
